DROP TABLE BASE_ADDRESS;
CREATE TABLE BASE_ADDRESS(
ID VARCHAR(50) PRIMARY KEY, 
ADDRESS VARCHAR(100) NOT NULL,
WALLET_ID VARCHAR(50) NULL,
KEY_PATH NVARCHAR(500) NULL,
NETWORK INTEGER NOT NULL DEFAULT(1), -- 1: Mainnet 2: Testnet(regtest)
NAME NVARCHAR(500) NULL, 
BALANCE REAL NOT NULL DEFAULT(0),
ACCOUNT NVARCHAR(200) NULL,
DESCRIPTION NVARCHAR(500) NULL,
CREATE_DATE DATETIME NOT NULL);


DROP TABLE BASE_WALLET;
CREATE TABLE BASE_WALLET(
ID VARCHAR(50) PRIMARY KEY, 
WALLET_NAME NVARCHAR(100) NOT NULL,
PASSWORD NVARCHAR(200) NOT NULL,
MNEMONIC_WORDS TEXT NULL, -- just for test, you should keep mnemonic words pirvately
DESCRIPTION NVARCHAR(500) NULL,
IS_ACTIVE BOOLEAN NOT NULL,
CREATE_DATE DATETIME NOT NULL);