//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USDTWallet.DataContext.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_WALLET
    {
        public string ID { get; set; }
        public string WALLET_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string MNEMONIC_WORDS { get; set; }
        public string DESCRIPTION { get; set; }
        public bool IS_ACTIVE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
    }
}
